export enum ClassKeys {
  BASE_PATH = 'BASE_PATH',
  MIDDLEWARE = 'MIDDLEWARE',
  ERROR_MIDDLEWARE = 'ERROR_MIDDLEWARE',
  WRAPPER = 'WRAPPER',
  CHILDREN = 'CHILDREN',
  OPTIONS = 'OPTIONS',
}

export enum RouteParamtypes {
  REQUEST = 'REQUEST',
  RESPONSE = 'RESPONSE',
  NEXT = 'NEXT',
  BODY = 'BODY',
  QUERY = 'QUERY',
  PARAM = 'PARAM',
  FILE = 'FILE',
  FILES = 'FILES',
  IP = 'IP',
  SESSION = 'SESSION',
  HEADERS = 'HEADERS',
  HOST = 'HOST',
  RATE_LIMIT = 'RATE_LIMIT',
  COOKIE = 'COOKIE',
}
